#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_PASANTIA01")]
	public partial class DbPasantiaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTBL_AREA(TBL_AREA instance);
    partial void UpdateTBL_AREA(TBL_AREA instance);
    partial void DeleteTBL_AREA(TBL_AREA instance);
    partial void InsertTBL_USUARIO(TBL_USUARIO instance);
    partial void UpdateTBL_USUARIO(TBL_USUARIO instance);
    partial void DeleteTBL_USUARIO(TBL_USUARIO instance);
    partial void InsertTBL_CARRERA(TBL_CARRERA instance);
    partial void UpdateTBL_CARRERA(TBL_CARRERA instance);
    partial void DeleteTBL_CARRERA(TBL_CARRERA instance);
    partial void InsertTBL_DOCENTE(TBL_DOCENTE instance);
    partial void UpdateTBL_DOCENTE(TBL_DOCENTE instance);
    partial void DeleteTBL_DOCENTE(TBL_DOCENTE instance);
    partial void InsertTBL_EMPRESA(TBL_EMPRESA instance);
    partial void UpdateTBL_EMPRESA(TBL_EMPRESA instance);
    partial void DeleteTBL_EMPRESA(TBL_EMPRESA instance);
    partial void InsertTBL_ESTUDIANTE(TBL_ESTUDIANTE instance);
    partial void UpdateTBL_ESTUDIANTE(TBL_ESTUDIANTE instance);
    partial void DeleteTBL_ESTUDIANTE(TBL_ESTUDIANTE instance);
    partial void InsertTBL_INSTITUCION(TBL_INSTITUCION instance);
    partial void UpdateTBL_INSTITUCION(TBL_INSTITUCION instance);
    partial void DeleteTBL_INSTITUCION(TBL_INSTITUCION instance);
    partial void InsertTBL_PASANTIA(TBL_PASANTIA instance);
    partial void UpdateTBL_PASANTIA(TBL_PASANTIA instance);
    partial void DeleteTBL_PASANTIA(TBL_PASANTIA instance);
    partial void InsertTBL_ROL(TBL_ROL instance);
    partial void UpdateTBL_ROL(TBL_ROL instance);
    partial void DeleteTBL_ROL(TBL_ROL instance);
    #endregion
		
		public DbPasantiaDataContext() : 
				base(global::DATA.Properties.Settings.Default.DB_PASANTIA01ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbPasantiaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbPasantiaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbPasantiaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbPasantiaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_AREA> TBL_AREAs
		{
			get
			{
				return this.GetTable<TBL_AREA>();
			}
		}
		
		public System.Data.Linq.Table<TBL_USUARIO> TBL_USUARIOs
		{
			get
			{
				return this.GetTable<TBL_USUARIO>();
			}
		}
		
		public System.Data.Linq.Table<TBL_CARRERA> TBL_CARRERAs
		{
			get
			{
				return this.GetTable<TBL_CARRERA>();
			}
		}
		
		public System.Data.Linq.Table<TBL_DOCENTE> TBL_DOCENTEs
		{
			get
			{
				return this.GetTable<TBL_DOCENTE>();
			}
		}
		
		public System.Data.Linq.Table<TBL_EMPRESA> TBL_EMPRESAs
		{
			get
			{
				return this.GetTable<TBL_EMPRESA>();
			}
		}
		
		public System.Data.Linq.Table<TBL_ESTUDIANTE> TBL_ESTUDIANTEs
		{
			get
			{
				return this.GetTable<TBL_ESTUDIANTE>();
			}
		}
		
		public System.Data.Linq.Table<TBL_INSTITUCION> TBL_INSTITUCIONs
		{
			get
			{
				return this.GetTable<TBL_INSTITUCION>();
			}
		}
		
		public System.Data.Linq.Table<TBL_PASANTIA> TBL_PASANTIAs
		{
			get
			{
				return this.GetTable<TBL_PASANTIA>();
			}
		}
		
		public System.Data.Linq.Table<TBL_ROL> TBL_ROLs
		{
			get
			{
				return this.GetTable<TBL_ROL>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_AREA")]
	public partial class TBL_AREA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _are_id;
		
		private string _are_descripcion;
		
		private char _are_status;
		
		private System.DateTime _are_add;
		
		private EntitySet<TBL_EMPRESA> _TBL_EMPRESAs;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onare_idChanging(int value);
    partial void Onare_idChanged();
    partial void Onare_descripcionChanging(string value);
    partial void Onare_descripcionChanged();
    partial void Onare_statusChanging(char value);
    partial void Onare_statusChanged();
    partial void Onare_addChanging(System.DateTime value);
    partial void Onare_addChanged();
    #endregion
		
		public TBL_AREA()
		{
			this._TBL_EMPRESAs = new EntitySet<TBL_EMPRESA>(new Action<TBL_EMPRESA>(this.attach_TBL_EMPRESAs), new Action<TBL_EMPRESA>(this.detach_TBL_EMPRESAs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_are_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int are_id
		{
			get
			{
				return this._are_id;
			}
			set
			{
				if ((this._are_id != value))
				{
					this.Onare_idChanging(value);
					this.SendPropertyChanging();
					this._are_id = value;
					this.SendPropertyChanged("are_id");
					this.Onare_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_are_descripcion", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string are_descripcion
		{
			get
			{
				return this._are_descripcion;
			}
			set
			{
				if ((this._are_descripcion != value))
				{
					this.Onare_descripcionChanging(value);
					this.SendPropertyChanging();
					this._are_descripcion = value;
					this.SendPropertyChanged("are_descripcion");
					this.Onare_descripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_are_status", DbType="Char(1) NOT NULL")]
		public char are_status
		{
			get
			{
				return this._are_status;
			}
			set
			{
				if ((this._are_status != value))
				{
					this.Onare_statusChanging(value);
					this.SendPropertyChanging();
					this._are_status = value;
					this.SendPropertyChanged("are_status");
					this.Onare_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_are_add", DbType="DateTime NOT NULL")]
		public System.DateTime are_add
		{
			get
			{
				return this._are_add;
			}
			set
			{
				if ((this._are_add != value))
				{
					this.Onare_addChanging(value);
					this.SendPropertyChanging();
					this._are_add = value;
					this.SendPropertyChanged("are_add");
					this.Onare_addChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_AREA_TBL_EMPRESA", Storage="_TBL_EMPRESAs", ThisKey="are_id", OtherKey="are_id")]
		public EntitySet<TBL_EMPRESA> TBL_EMPRESAs
		{
			get
			{
				return this._TBL_EMPRESAs;
			}
			set
			{
				this._TBL_EMPRESAs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_EMPRESAs(TBL_EMPRESA entity)
		{
			this.SendPropertyChanging();
			entity.TBL_AREA = this;
		}
		
		private void detach_TBL_EMPRESAs(TBL_EMPRESA entity)
		{
			this.SendPropertyChanging();
			entity.TBL_AREA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_USUARIO")]
	public partial class TBL_USUARIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _usu_id;
		
		private string _usu_apellidos;
		
		private string _usu_nombres;
		
		private string _usu_username;
		
		private string _usu_password;
		
		private char _usu_status;
		
		private System.DateTime _usu_add;
		
		private System.Nullable<int> _rol_id;
		
		private EntityRef<TBL_ROL> _TBL_ROL;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onusu_idChanging(int value);
    partial void Onusu_idChanged();
    partial void Onusu_apellidosChanging(string value);
    partial void Onusu_apellidosChanged();
    partial void Onusu_nombresChanging(string value);
    partial void Onusu_nombresChanged();
    partial void Onusu_usernameChanging(string value);
    partial void Onusu_usernameChanged();
    partial void Onusu_passwordChanging(string value);
    partial void Onusu_passwordChanged();
    partial void Onusu_statusChanging(char value);
    partial void Onusu_statusChanged();
    partial void Onusu_addChanging(System.DateTime value);
    partial void Onusu_addChanged();
    partial void Onrol_idChanging(System.Nullable<int> value);
    partial void Onrol_idChanged();
    #endregion
		
		public TBL_USUARIO()
		{
			this._TBL_ROL = default(EntityRef<TBL_ROL>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int usu_id
		{
			get
			{
				return this._usu_id;
			}
			set
			{
				if ((this._usu_id != value))
				{
					this.Onusu_idChanging(value);
					this.SendPropertyChanging();
					this._usu_id = value;
					this.SendPropertyChanged("usu_id");
					this.Onusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_apellidos", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string usu_apellidos
		{
			get
			{
				return this._usu_apellidos;
			}
			set
			{
				if ((this._usu_apellidos != value))
				{
					this.Onusu_apellidosChanging(value);
					this.SendPropertyChanging();
					this._usu_apellidos = value;
					this.SendPropertyChanged("usu_apellidos");
					this.Onusu_apellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_nombres", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string usu_nombres
		{
			get
			{
				return this._usu_nombres;
			}
			set
			{
				if ((this._usu_nombres != value))
				{
					this.Onusu_nombresChanging(value);
					this.SendPropertyChanging();
					this._usu_nombres = value;
					this.SendPropertyChanged("usu_nombres");
					this.Onusu_nombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_username", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string usu_username
		{
			get
			{
				return this._usu_username;
			}
			set
			{
				if ((this._usu_username != value))
				{
					this.Onusu_usernameChanging(value);
					this.SendPropertyChanging();
					this._usu_username = value;
					this.SendPropertyChanged("usu_username");
					this.Onusu_usernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_password", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string usu_password
		{
			get
			{
				return this._usu_password;
			}
			set
			{
				if ((this._usu_password != value))
				{
					this.Onusu_passwordChanging(value);
					this.SendPropertyChanging();
					this._usu_password = value;
					this.SendPropertyChanged("usu_password");
					this.Onusu_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_status", DbType="Char(1) NOT NULL")]
		public char usu_status
		{
			get
			{
				return this._usu_status;
			}
			set
			{
				if ((this._usu_status != value))
				{
					this.Onusu_statusChanging(value);
					this.SendPropertyChanging();
					this._usu_status = value;
					this.SendPropertyChanged("usu_status");
					this.Onusu_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_add", DbType="DateTime NOT NULL")]
		public System.DateTime usu_add
		{
			get
			{
				return this._usu_add;
			}
			set
			{
				if ((this._usu_add != value))
				{
					this.Onusu_addChanging(value);
					this.SendPropertyChanging();
					this._usu_add = value;
					this.SendPropertyChanged("usu_add");
					this.Onusu_addChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol_id", DbType="Int")]
		public System.Nullable<int> rol_id
		{
			get
			{
				return this._rol_id;
			}
			set
			{
				if ((this._rol_id != value))
				{
					if (this._TBL_ROL.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onrol_idChanging(value);
					this.SendPropertyChanging();
					this._rol_id = value;
					this.SendPropertyChanged("rol_id");
					this.Onrol_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_ROL_TBL_USUARIO", Storage="_TBL_ROL", ThisKey="rol_id", OtherKey="rol_id", IsForeignKey=true)]
		public TBL_ROL TBL_ROL
		{
			get
			{
				return this._TBL_ROL.Entity;
			}
			set
			{
				TBL_ROL previousValue = this._TBL_ROL.Entity;
				if (((previousValue != value) 
							|| (this._TBL_ROL.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_ROL.Entity = null;
						previousValue.TBL_USUARIOs.Remove(this);
					}
					this._TBL_ROL.Entity = value;
					if ((value != null))
					{
						value.TBL_USUARIOs.Add(this);
						this._rol_id = value.rol_id;
					}
					else
					{
						this._rol_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("TBL_ROL");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_CARRERA")]
	public partial class TBL_CARRERA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private byte _car_id;
		
		private string _car_nombre;
		
		private string _car_campus;
		
		private string _car_direccion;
		
		private char _car_status;
		
		private System.DateTime _car_add;
		
		private byte _inst_id;
		
		private EntitySet<TBL_ESTUDIANTE> _TBL_ESTUDIANTEs;
		
		private EntityRef<TBL_INSTITUCION> _TBL_INSTITUCION;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncar_idChanging(byte value);
    partial void Oncar_idChanged();
    partial void Oncar_nombreChanging(string value);
    partial void Oncar_nombreChanged();
    partial void Oncar_campusChanging(string value);
    partial void Oncar_campusChanged();
    partial void Oncar_direccionChanging(string value);
    partial void Oncar_direccionChanged();
    partial void Oncar_statusChanging(char value);
    partial void Oncar_statusChanged();
    partial void Oncar_addChanging(System.DateTime value);
    partial void Oncar_addChanged();
    partial void Oninst_idChanging(byte value);
    partial void Oninst_idChanged();
    #endregion
		
		public TBL_CARRERA()
		{
			this._TBL_ESTUDIANTEs = new EntitySet<TBL_ESTUDIANTE>(new Action<TBL_ESTUDIANTE>(this.attach_TBL_ESTUDIANTEs), new Action<TBL_ESTUDIANTE>(this.detach_TBL_ESTUDIANTEs));
			this._TBL_INSTITUCION = default(EntityRef<TBL_INSTITUCION>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_id", AutoSync=AutoSync.OnInsert, DbType="TinyInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public byte car_id
		{
			get
			{
				return this._car_id;
			}
			set
			{
				if ((this._car_id != value))
				{
					this.Oncar_idChanging(value);
					this.SendPropertyChanging();
					this._car_id = value;
					this.SendPropertyChanged("car_id");
					this.Oncar_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string car_nombre
		{
			get
			{
				return this._car_nombre;
			}
			set
			{
				if ((this._car_nombre != value))
				{
					this.Oncar_nombreChanging(value);
					this.SendPropertyChanging();
					this._car_nombre = value;
					this.SendPropertyChanged("car_nombre");
					this.Oncar_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_campus", DbType="VarChar(100)")]
		public string car_campus
		{
			get
			{
				return this._car_campus;
			}
			set
			{
				if ((this._car_campus != value))
				{
					this.Oncar_campusChanging(value);
					this.SendPropertyChanging();
					this._car_campus = value;
					this.SendPropertyChanged("car_campus");
					this.Oncar_campusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_direccion", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string car_direccion
		{
			get
			{
				return this._car_direccion;
			}
			set
			{
				if ((this._car_direccion != value))
				{
					this.Oncar_direccionChanging(value);
					this.SendPropertyChanging();
					this._car_direccion = value;
					this.SendPropertyChanged("car_direccion");
					this.Oncar_direccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_status", DbType="Char(1) NOT NULL")]
		public char car_status
		{
			get
			{
				return this._car_status;
			}
			set
			{
				if ((this._car_status != value))
				{
					this.Oncar_statusChanging(value);
					this.SendPropertyChanging();
					this._car_status = value;
					this.SendPropertyChanged("car_status");
					this.Oncar_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_add", DbType="DateTime NOT NULL")]
		public System.DateTime car_add
		{
			get
			{
				return this._car_add;
			}
			set
			{
				if ((this._car_add != value))
				{
					this.Oncar_addChanging(value);
					this.SendPropertyChanging();
					this._car_add = value;
					this.SendPropertyChanged("car_add");
					this.Oncar_addChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inst_id", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte inst_id
		{
			get
			{
				return this._inst_id;
			}
			set
			{
				if ((this._inst_id != value))
				{
					if (this._TBL_INSTITUCION.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oninst_idChanging(value);
					this.SendPropertyChanging();
					this._inst_id = value;
					this.SendPropertyChanged("inst_id");
					this.Oninst_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_CARRERA_TBL_ESTUDIANTE", Storage="_TBL_ESTUDIANTEs", ThisKey="car_id,inst_id", OtherKey="car_id,inst_id")]
		public EntitySet<TBL_ESTUDIANTE> TBL_ESTUDIANTEs
		{
			get
			{
				return this._TBL_ESTUDIANTEs;
			}
			set
			{
				this._TBL_ESTUDIANTEs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_INSTITUCION_TBL_CARRERA", Storage="_TBL_INSTITUCION", ThisKey="inst_id", OtherKey="inst_id", IsForeignKey=true)]
		public TBL_INSTITUCION TBL_INSTITUCION
		{
			get
			{
				return this._TBL_INSTITUCION.Entity;
			}
			set
			{
				TBL_INSTITUCION previousValue = this._TBL_INSTITUCION.Entity;
				if (((previousValue != value) 
							|| (this._TBL_INSTITUCION.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_INSTITUCION.Entity = null;
						previousValue.TBL_CARRERAs.Remove(this);
					}
					this._TBL_INSTITUCION.Entity = value;
					if ((value != null))
					{
						value.TBL_CARRERAs.Add(this);
						this._inst_id = value.inst_id;
					}
					else
					{
						this._inst_id = default(byte);
					}
					this.SendPropertyChanged("TBL_INSTITUCION");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_ESTUDIANTEs(TBL_ESTUDIANTE entity)
		{
			this.SendPropertyChanging();
			entity.TBL_CARRERA = this;
		}
		
		private void detach_TBL_ESTUDIANTEs(TBL_ESTUDIANTE entity)
		{
			this.SendPropertyChanging();
			entity.TBL_CARRERA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_DOCENTE")]
	public partial class TBL_DOCENTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _doc_id;
		
		private char _doc_tipoidentificacion;
		
		private string _doc_identificacion;
		
		private string _doc_apellidos;
		
		private string _doc_nombres;
		
		private string _doc_direccion;
		
		private string _doc_telefono;
		
		private char _doc_status;
		
		private System.DateTime _doc_add;
		
		private EntitySet<TBL_PASANTIA> _TBL_PASANTIAs;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondoc_idChanging(int value);
    partial void Ondoc_idChanged();
    partial void Ondoc_tipoidentificacionChanging(char value);
    partial void Ondoc_tipoidentificacionChanged();
    partial void Ondoc_identificacionChanging(string value);
    partial void Ondoc_identificacionChanged();
    partial void Ondoc_apellidosChanging(string value);
    partial void Ondoc_apellidosChanged();
    partial void Ondoc_nombresChanging(string value);
    partial void Ondoc_nombresChanged();
    partial void Ondoc_direccionChanging(string value);
    partial void Ondoc_direccionChanged();
    partial void Ondoc_telefonoChanging(string value);
    partial void Ondoc_telefonoChanged();
    partial void Ondoc_statusChanging(char value);
    partial void Ondoc_statusChanged();
    partial void Ondoc_addChanging(System.DateTime value);
    partial void Ondoc_addChanged();
    #endregion
		
		public TBL_DOCENTE()
		{
			this._TBL_PASANTIAs = new EntitySet<TBL_PASANTIA>(new Action<TBL_PASANTIA>(this.attach_TBL_PASANTIAs), new Action<TBL_PASANTIA>(this.detach_TBL_PASANTIAs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doc_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int doc_id
		{
			get
			{
				return this._doc_id;
			}
			set
			{
				if ((this._doc_id != value))
				{
					this.Ondoc_idChanging(value);
					this.SendPropertyChanging();
					this._doc_id = value;
					this.SendPropertyChanged("doc_id");
					this.Ondoc_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doc_tipoidentificacion", DbType="Char(1) NOT NULL")]
		public char doc_tipoidentificacion
		{
			get
			{
				return this._doc_tipoidentificacion;
			}
			set
			{
				if ((this._doc_tipoidentificacion != value))
				{
					this.Ondoc_tipoidentificacionChanging(value);
					this.SendPropertyChanging();
					this._doc_tipoidentificacion = value;
					this.SendPropertyChanged("doc_tipoidentificacion");
					this.Ondoc_tipoidentificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doc_identificacion", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string doc_identificacion
		{
			get
			{
				return this._doc_identificacion;
			}
			set
			{
				if ((this._doc_identificacion != value))
				{
					this.Ondoc_identificacionChanging(value);
					this.SendPropertyChanging();
					this._doc_identificacion = value;
					this.SendPropertyChanged("doc_identificacion");
					this.Ondoc_identificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doc_apellidos", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string doc_apellidos
		{
			get
			{
				return this._doc_apellidos;
			}
			set
			{
				if ((this._doc_apellidos != value))
				{
					this.Ondoc_apellidosChanging(value);
					this.SendPropertyChanging();
					this._doc_apellidos = value;
					this.SendPropertyChanged("doc_apellidos");
					this.Ondoc_apellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doc_nombres", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string doc_nombres
		{
			get
			{
				return this._doc_nombres;
			}
			set
			{
				if ((this._doc_nombres != value))
				{
					this.Ondoc_nombresChanging(value);
					this.SendPropertyChanging();
					this._doc_nombres = value;
					this.SendPropertyChanged("doc_nombres");
					this.Ondoc_nombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doc_direccion", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string doc_direccion
		{
			get
			{
				return this._doc_direccion;
			}
			set
			{
				if ((this._doc_direccion != value))
				{
					this.Ondoc_direccionChanging(value);
					this.SendPropertyChanging();
					this._doc_direccion = value;
					this.SendPropertyChanged("doc_direccion");
					this.Ondoc_direccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doc_telefono", DbType="VarChar(10)")]
		public string doc_telefono
		{
			get
			{
				return this._doc_telefono;
			}
			set
			{
				if ((this._doc_telefono != value))
				{
					this.Ondoc_telefonoChanging(value);
					this.SendPropertyChanging();
					this._doc_telefono = value;
					this.SendPropertyChanged("doc_telefono");
					this.Ondoc_telefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doc_status", DbType="Char(1) NOT NULL")]
		public char doc_status
		{
			get
			{
				return this._doc_status;
			}
			set
			{
				if ((this._doc_status != value))
				{
					this.Ondoc_statusChanging(value);
					this.SendPropertyChanging();
					this._doc_status = value;
					this.SendPropertyChanged("doc_status");
					this.Ondoc_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doc_add", DbType="DateTime NOT NULL")]
		public System.DateTime doc_add
		{
			get
			{
				return this._doc_add;
			}
			set
			{
				if ((this._doc_add != value))
				{
					this.Ondoc_addChanging(value);
					this.SendPropertyChanging();
					this._doc_add = value;
					this.SendPropertyChanged("doc_add");
					this.Ondoc_addChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_DOCENTE_TBL_PASANTIA", Storage="_TBL_PASANTIAs", ThisKey="doc_id", OtherKey="doc_id")]
		public EntitySet<TBL_PASANTIA> TBL_PASANTIAs
		{
			get
			{
				return this._TBL_PASANTIAs;
			}
			set
			{
				this._TBL_PASANTIAs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_PASANTIAs(TBL_PASANTIA entity)
		{
			this.SendPropertyChanging();
			entity.TBL_DOCENTE = this;
		}
		
		private void detach_TBL_PASANTIAs(TBL_PASANTIA entity)
		{
			this.SendPropertyChanging();
			entity.TBL_DOCENTE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_EMPRESA")]
	public partial class TBL_EMPRESA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _emp_id;
		
		private string _emp_nombre;
		
		private string _emp_ruc;
		
		private string _emp_postal;
		
		private string _emp_telefono;
		
		private string _emp_representante;
		
		private string _emp_email;
		
		private int _are_id;
		
		private string _emp_calleprincipal;
		
		private string _emp_callesecundaria;
		
		private System.Nullable<double> _emp_longitud;
		
		private System.Nullable<double> _emp_latitud;
		
		private string _emp_referencia;
		
		private char _emp_status;
		
		private System.DateTime _emp_add;
		
		private EntitySet<TBL_PASANTIA> _TBL_PASANTIAs;
		
		private EntityRef<TBL_AREA> _TBL_AREA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onemp_idChanging(int value);
    partial void Onemp_idChanged();
    partial void Onemp_nombreChanging(string value);
    partial void Onemp_nombreChanged();
    partial void Onemp_rucChanging(string value);
    partial void Onemp_rucChanged();
    partial void Onemp_postalChanging(string value);
    partial void Onemp_postalChanged();
    partial void Onemp_telefonoChanging(string value);
    partial void Onemp_telefonoChanged();
    partial void Onemp_representanteChanging(string value);
    partial void Onemp_representanteChanged();
    partial void Onemp_emailChanging(string value);
    partial void Onemp_emailChanged();
    partial void Onare_idChanging(int value);
    partial void Onare_idChanged();
    partial void Onemp_calleprincipalChanging(string value);
    partial void Onemp_calleprincipalChanged();
    partial void Onemp_callesecundariaChanging(string value);
    partial void Onemp_callesecundariaChanged();
    partial void Onemp_longitudChanging(System.Nullable<double> value);
    partial void Onemp_longitudChanged();
    partial void Onemp_latitudChanging(System.Nullable<double> value);
    partial void Onemp_latitudChanged();
    partial void Onemp_referenciaChanging(string value);
    partial void Onemp_referenciaChanged();
    partial void Onemp_statusChanging(char value);
    partial void Onemp_statusChanged();
    partial void Onemp_addChanging(System.DateTime value);
    partial void Onemp_addChanged();
    #endregion
		
		public TBL_EMPRESA()
		{
			this._TBL_PASANTIAs = new EntitySet<TBL_PASANTIA>(new Action<TBL_PASANTIA>(this.attach_TBL_PASANTIAs), new Action<TBL_PASANTIA>(this.detach_TBL_PASANTIAs));
			this._TBL_AREA = default(EntityRef<TBL_AREA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int emp_id
		{
			get
			{
				return this._emp_id;
			}
			set
			{
				if ((this._emp_id != value))
				{
					this.Onemp_idChanging(value);
					this.SendPropertyChanging();
					this._emp_id = value;
					this.SendPropertyChanged("emp_id");
					this.Onemp_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string emp_nombre
		{
			get
			{
				return this._emp_nombre;
			}
			set
			{
				if ((this._emp_nombre != value))
				{
					this.Onemp_nombreChanging(value);
					this.SendPropertyChanging();
					this._emp_nombre = value;
					this.SendPropertyChanged("emp_nombre");
					this.Onemp_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_ruc", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
		public string emp_ruc
		{
			get
			{
				return this._emp_ruc;
			}
			set
			{
				if ((this._emp_ruc != value))
				{
					this.Onemp_rucChanging(value);
					this.SendPropertyChanging();
					this._emp_ruc = value;
					this.SendPropertyChanged("emp_ruc");
					this.Onemp_rucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_postal", DbType="VarChar(8)")]
		public string emp_postal
		{
			get
			{
				return this._emp_postal;
			}
			set
			{
				if ((this._emp_postal != value))
				{
					this.Onemp_postalChanging(value);
					this.SendPropertyChanging();
					this._emp_postal = value;
					this.SendPropertyChanged("emp_postal");
					this.Onemp_postalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_telefono", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string emp_telefono
		{
			get
			{
				return this._emp_telefono;
			}
			set
			{
				if ((this._emp_telefono != value))
				{
					this.Onemp_telefonoChanging(value);
					this.SendPropertyChanging();
					this._emp_telefono = value;
					this.SendPropertyChanged("emp_telefono");
					this.Onemp_telefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_representante", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string emp_representante
		{
			get
			{
				return this._emp_representante;
			}
			set
			{
				if ((this._emp_representante != value))
				{
					this.Onemp_representanteChanging(value);
					this.SendPropertyChanging();
					this._emp_representante = value;
					this.SendPropertyChanged("emp_representante");
					this.Onemp_representanteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_email", DbType="VarChar(100)")]
		public string emp_email
		{
			get
			{
				return this._emp_email;
			}
			set
			{
				if ((this._emp_email != value))
				{
					this.Onemp_emailChanging(value);
					this.SendPropertyChanging();
					this._emp_email = value;
					this.SendPropertyChanged("emp_email");
					this.Onemp_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_are_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int are_id
		{
			get
			{
				return this._are_id;
			}
			set
			{
				if ((this._are_id != value))
				{
					if (this._TBL_AREA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onare_idChanging(value);
					this.SendPropertyChanging();
					this._are_id = value;
					this.SendPropertyChanged("are_id");
					this.Onare_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_calleprincipal", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string emp_calleprincipal
		{
			get
			{
				return this._emp_calleprincipal;
			}
			set
			{
				if ((this._emp_calleprincipal != value))
				{
					this.Onemp_calleprincipalChanging(value);
					this.SendPropertyChanging();
					this._emp_calleprincipal = value;
					this.SendPropertyChanged("emp_calleprincipal");
					this.Onemp_calleprincipalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_callesecundaria", DbType="VarChar(200)")]
		public string emp_callesecundaria
		{
			get
			{
				return this._emp_callesecundaria;
			}
			set
			{
				if ((this._emp_callesecundaria != value))
				{
					this.Onemp_callesecundariaChanging(value);
					this.SendPropertyChanging();
					this._emp_callesecundaria = value;
					this.SendPropertyChanged("emp_callesecundaria");
					this.Onemp_callesecundariaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_longitud", DbType="Float")]
		public System.Nullable<double> emp_longitud
		{
			get
			{
				return this._emp_longitud;
			}
			set
			{
				if ((this._emp_longitud != value))
				{
					this.Onemp_longitudChanging(value);
					this.SendPropertyChanging();
					this._emp_longitud = value;
					this.SendPropertyChanged("emp_longitud");
					this.Onemp_longitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_latitud", DbType="Float")]
		public System.Nullable<double> emp_latitud
		{
			get
			{
				return this._emp_latitud;
			}
			set
			{
				if ((this._emp_latitud != value))
				{
					this.Onemp_latitudChanging(value);
					this.SendPropertyChanging();
					this._emp_latitud = value;
					this.SendPropertyChanged("emp_latitud");
					this.Onemp_latitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_referencia", DbType="VarChar(200)")]
		public string emp_referencia
		{
			get
			{
				return this._emp_referencia;
			}
			set
			{
				if ((this._emp_referencia != value))
				{
					this.Onemp_referenciaChanging(value);
					this.SendPropertyChanging();
					this._emp_referencia = value;
					this.SendPropertyChanged("emp_referencia");
					this.Onemp_referenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_status", DbType="Char(1) NOT NULL")]
		public char emp_status
		{
			get
			{
				return this._emp_status;
			}
			set
			{
				if ((this._emp_status != value))
				{
					this.Onemp_statusChanging(value);
					this.SendPropertyChanging();
					this._emp_status = value;
					this.SendPropertyChanged("emp_status");
					this.Onemp_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_add", DbType="DateTime NOT NULL")]
		public System.DateTime emp_add
		{
			get
			{
				return this._emp_add;
			}
			set
			{
				if ((this._emp_add != value))
				{
					this.Onemp_addChanging(value);
					this.SendPropertyChanging();
					this._emp_add = value;
					this.SendPropertyChanged("emp_add");
					this.Onemp_addChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_EMPRESA_TBL_PASANTIA", Storage="_TBL_PASANTIAs", ThisKey="emp_id,are_id", OtherKey="emp_id,are_id")]
		public EntitySet<TBL_PASANTIA> TBL_PASANTIAs
		{
			get
			{
				return this._TBL_PASANTIAs;
			}
			set
			{
				this._TBL_PASANTIAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_AREA_TBL_EMPRESA", Storage="_TBL_AREA", ThisKey="are_id", OtherKey="are_id", IsForeignKey=true)]
		public TBL_AREA TBL_AREA
		{
			get
			{
				return this._TBL_AREA.Entity;
			}
			set
			{
				TBL_AREA previousValue = this._TBL_AREA.Entity;
				if (((previousValue != value) 
							|| (this._TBL_AREA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_AREA.Entity = null;
						previousValue.TBL_EMPRESAs.Remove(this);
					}
					this._TBL_AREA.Entity = value;
					if ((value != null))
					{
						value.TBL_EMPRESAs.Add(this);
						this._are_id = value.are_id;
					}
					else
					{
						this._are_id = default(int);
					}
					this.SendPropertyChanged("TBL_AREA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_PASANTIAs(TBL_PASANTIA entity)
		{
			this.SendPropertyChanging();
			entity.TBL_EMPRESA = this;
		}
		
		private void detach_TBL_PASANTIAs(TBL_PASANTIA entity)
		{
			this.SendPropertyChanging();
			entity.TBL_EMPRESA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_ESTUDIANTE")]
	public partial class TBL_ESTUDIANTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _est_id;
		
		private char _est_tipoidentificacion;
		
		private string _est_identificacion;
		
		private string _est_apellidos;
		
		private string _est_nombres;
		
		private string _est_direccion;
		
		private string _est_telefono;
		
		private string _est_celular;
		
		private string _est_email;
		
		private char _est_genero;
		
		private char _est_status;
		
		private System.DateTime _est_add;
		
		private byte _car_id;
		
		private byte _inst_id;
		
		private EntitySet<TBL_PASANTIA> _TBL_PASANTIAs;
		
		private EntityRef<TBL_CARRERA> _TBL_CARRERA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onest_idChanging(int value);
    partial void Onest_idChanged();
    partial void Onest_tipoidentificacionChanging(char value);
    partial void Onest_tipoidentificacionChanged();
    partial void Onest_identificacionChanging(string value);
    partial void Onest_identificacionChanged();
    partial void Onest_apellidosChanging(string value);
    partial void Onest_apellidosChanged();
    partial void Onest_nombresChanging(string value);
    partial void Onest_nombresChanged();
    partial void Onest_direccionChanging(string value);
    partial void Onest_direccionChanged();
    partial void Onest_telefonoChanging(string value);
    partial void Onest_telefonoChanged();
    partial void Onest_celularChanging(string value);
    partial void Onest_celularChanged();
    partial void Onest_emailChanging(string value);
    partial void Onest_emailChanged();
    partial void Onest_generoChanging(char value);
    partial void Onest_generoChanged();
    partial void Onest_statusChanging(char value);
    partial void Onest_statusChanged();
    partial void Onest_addChanging(System.DateTime value);
    partial void Onest_addChanged();
    partial void Oncar_idChanging(byte value);
    partial void Oncar_idChanged();
    partial void Oninst_idChanging(byte value);
    partial void Oninst_idChanged();
    #endregion
		
		public TBL_ESTUDIANTE()
		{
			this._TBL_PASANTIAs = new EntitySet<TBL_PASANTIA>(new Action<TBL_PASANTIA>(this.attach_TBL_PASANTIAs), new Action<TBL_PASANTIA>(this.detach_TBL_PASANTIAs));
			this._TBL_CARRERA = default(EntityRef<TBL_CARRERA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int est_id
		{
			get
			{
				return this._est_id;
			}
			set
			{
				if ((this._est_id != value))
				{
					this.Onest_idChanging(value);
					this.SendPropertyChanging();
					this._est_id = value;
					this.SendPropertyChanged("est_id");
					this.Onest_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_tipoidentificacion", DbType="Char(1) NOT NULL")]
		public char est_tipoidentificacion
		{
			get
			{
				return this._est_tipoidentificacion;
			}
			set
			{
				if ((this._est_tipoidentificacion != value))
				{
					this.Onest_tipoidentificacionChanging(value);
					this.SendPropertyChanging();
					this._est_tipoidentificacion = value;
					this.SendPropertyChanged("est_tipoidentificacion");
					this.Onest_tipoidentificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_identificacion", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string est_identificacion
		{
			get
			{
				return this._est_identificacion;
			}
			set
			{
				if ((this._est_identificacion != value))
				{
					this.Onest_identificacionChanging(value);
					this.SendPropertyChanging();
					this._est_identificacion = value;
					this.SendPropertyChanged("est_identificacion");
					this.Onest_identificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_apellidos", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string est_apellidos
		{
			get
			{
				return this._est_apellidos;
			}
			set
			{
				if ((this._est_apellidos != value))
				{
					this.Onest_apellidosChanging(value);
					this.SendPropertyChanging();
					this._est_apellidos = value;
					this.SendPropertyChanged("est_apellidos");
					this.Onest_apellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_nombres", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string est_nombres
		{
			get
			{
				return this._est_nombres;
			}
			set
			{
				if ((this._est_nombres != value))
				{
					this.Onest_nombresChanging(value);
					this.SendPropertyChanging();
					this._est_nombres = value;
					this.SendPropertyChanged("est_nombres");
					this.Onest_nombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_direccion", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string est_direccion
		{
			get
			{
				return this._est_direccion;
			}
			set
			{
				if ((this._est_direccion != value))
				{
					this.Onest_direccionChanging(value);
					this.SendPropertyChanging();
					this._est_direccion = value;
					this.SendPropertyChanged("est_direccion");
					this.Onest_direccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_telefono", DbType="VarChar(10)")]
		public string est_telefono
		{
			get
			{
				return this._est_telefono;
			}
			set
			{
				if ((this._est_telefono != value))
				{
					this.Onest_telefonoChanging(value);
					this.SendPropertyChanging();
					this._est_telefono = value;
					this.SendPropertyChanged("est_telefono");
					this.Onest_telefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_celular", DbType="VarChar(10)")]
		public string est_celular
		{
			get
			{
				return this._est_celular;
			}
			set
			{
				if ((this._est_celular != value))
				{
					this.Onest_celularChanging(value);
					this.SendPropertyChanging();
					this._est_celular = value;
					this.SendPropertyChanged("est_celular");
					this.Onest_celularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_email", DbType="VarChar(100)")]
		public string est_email
		{
			get
			{
				return this._est_email;
			}
			set
			{
				if ((this._est_email != value))
				{
					this.Onest_emailChanging(value);
					this.SendPropertyChanging();
					this._est_email = value;
					this.SendPropertyChanged("est_email");
					this.Onest_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_genero", DbType="Char(1) NOT NULL")]
		public char est_genero
		{
			get
			{
				return this._est_genero;
			}
			set
			{
				if ((this._est_genero != value))
				{
					this.Onest_generoChanging(value);
					this.SendPropertyChanging();
					this._est_genero = value;
					this.SendPropertyChanged("est_genero");
					this.Onest_generoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_status", DbType="Char(1) NOT NULL")]
		public char est_status
		{
			get
			{
				return this._est_status;
			}
			set
			{
				if ((this._est_status != value))
				{
					this.Onest_statusChanging(value);
					this.SendPropertyChanging();
					this._est_status = value;
					this.SendPropertyChanged("est_status");
					this.Onest_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_add", DbType="DateTime NOT NULL")]
		public System.DateTime est_add
		{
			get
			{
				return this._est_add;
			}
			set
			{
				if ((this._est_add != value))
				{
					this.Onest_addChanging(value);
					this.SendPropertyChanging();
					this._est_add = value;
					this.SendPropertyChanged("est_add");
					this.Onest_addChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_id", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte car_id
		{
			get
			{
				return this._car_id;
			}
			set
			{
				if ((this._car_id != value))
				{
					if (this._TBL_CARRERA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncar_idChanging(value);
					this.SendPropertyChanging();
					this._car_id = value;
					this.SendPropertyChanged("car_id");
					this.Oncar_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inst_id", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte inst_id
		{
			get
			{
				return this._inst_id;
			}
			set
			{
				if ((this._inst_id != value))
				{
					if (this._TBL_CARRERA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oninst_idChanging(value);
					this.SendPropertyChanging();
					this._inst_id = value;
					this.SendPropertyChanged("inst_id");
					this.Oninst_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_ESTUDIANTE_TBL_PASANTIA", Storage="_TBL_PASANTIAs", ThisKey="est_id,car_id,inst_id", OtherKey="est_id,car_id,inst_id")]
		public EntitySet<TBL_PASANTIA> TBL_PASANTIAs
		{
			get
			{
				return this._TBL_PASANTIAs;
			}
			set
			{
				this._TBL_PASANTIAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_CARRERA_TBL_ESTUDIANTE", Storage="_TBL_CARRERA", ThisKey="car_id,inst_id", OtherKey="car_id,inst_id", IsForeignKey=true)]
		public TBL_CARRERA TBL_CARRERA
		{
			get
			{
				return this._TBL_CARRERA.Entity;
			}
			set
			{
				TBL_CARRERA previousValue = this._TBL_CARRERA.Entity;
				if (((previousValue != value) 
							|| (this._TBL_CARRERA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_CARRERA.Entity = null;
						previousValue.TBL_ESTUDIANTEs.Remove(this);
					}
					this._TBL_CARRERA.Entity = value;
					if ((value != null))
					{
						value.TBL_ESTUDIANTEs.Add(this);
						this._car_id = value.car_id;
						this._inst_id = value.inst_id;
					}
					else
					{
						this._car_id = default(byte);
						this._inst_id = default(byte);
					}
					this.SendPropertyChanged("TBL_CARRERA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_PASANTIAs(TBL_PASANTIA entity)
		{
			this.SendPropertyChanging();
			entity.TBL_ESTUDIANTE = this;
		}
		
		private void detach_TBL_PASANTIAs(TBL_PASANTIA entity)
		{
			this.SendPropertyChanging();
			entity.TBL_ESTUDIANTE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_INSTITUCION")]
	public partial class TBL_INSTITUCION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private byte _inst_id;
		
		private string _inst_nombre;
		
		private string _inst_direcciom;
		
		private string _inst_telefono;
		
		private char _inst_status;
		
		private System.DateTime _inst_add;
		
		private EntitySet<TBL_CARRERA> _TBL_CARRERAs;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oninst_idChanging(byte value);
    partial void Oninst_idChanged();
    partial void Oninst_nombreChanging(string value);
    partial void Oninst_nombreChanged();
    partial void Oninst_direcciomChanging(string value);
    partial void Oninst_direcciomChanged();
    partial void Oninst_telefonoChanging(string value);
    partial void Oninst_telefonoChanged();
    partial void Oninst_statusChanging(char value);
    partial void Oninst_statusChanged();
    partial void Oninst_addChanging(System.DateTime value);
    partial void Oninst_addChanged();
    #endregion
		
		public TBL_INSTITUCION()
		{
			this._TBL_CARRERAs = new EntitySet<TBL_CARRERA>(new Action<TBL_CARRERA>(this.attach_TBL_CARRERAs), new Action<TBL_CARRERA>(this.detach_TBL_CARRERAs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inst_id", AutoSync=AutoSync.OnInsert, DbType="TinyInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public byte inst_id
		{
			get
			{
				return this._inst_id;
			}
			set
			{
				if ((this._inst_id != value))
				{
					this.Oninst_idChanging(value);
					this.SendPropertyChanging();
					this._inst_id = value;
					this.SendPropertyChanged("inst_id");
					this.Oninst_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inst_nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string inst_nombre
		{
			get
			{
				return this._inst_nombre;
			}
			set
			{
				if ((this._inst_nombre != value))
				{
					this.Oninst_nombreChanging(value);
					this.SendPropertyChanging();
					this._inst_nombre = value;
					this.SendPropertyChanged("inst_nombre");
					this.Oninst_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inst_direcciom", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string inst_direcciom
		{
			get
			{
				return this._inst_direcciom;
			}
			set
			{
				if ((this._inst_direcciom != value))
				{
					this.Oninst_direcciomChanging(value);
					this.SendPropertyChanging();
					this._inst_direcciom = value;
					this.SendPropertyChanged("inst_direcciom");
					this.Oninst_direcciomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inst_telefono", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string inst_telefono
		{
			get
			{
				return this._inst_telefono;
			}
			set
			{
				if ((this._inst_telefono != value))
				{
					this.Oninst_telefonoChanging(value);
					this.SendPropertyChanging();
					this._inst_telefono = value;
					this.SendPropertyChanged("inst_telefono");
					this.Oninst_telefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inst_status", DbType="Char(1) NOT NULL")]
		public char inst_status
		{
			get
			{
				return this._inst_status;
			}
			set
			{
				if ((this._inst_status != value))
				{
					this.Oninst_statusChanging(value);
					this.SendPropertyChanging();
					this._inst_status = value;
					this.SendPropertyChanged("inst_status");
					this.Oninst_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inst_add", DbType="DateTime NOT NULL")]
		public System.DateTime inst_add
		{
			get
			{
				return this._inst_add;
			}
			set
			{
				if ((this._inst_add != value))
				{
					this.Oninst_addChanging(value);
					this.SendPropertyChanging();
					this._inst_add = value;
					this.SendPropertyChanged("inst_add");
					this.Oninst_addChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_INSTITUCION_TBL_CARRERA", Storage="_TBL_CARRERAs", ThisKey="inst_id", OtherKey="inst_id")]
		public EntitySet<TBL_CARRERA> TBL_CARRERAs
		{
			get
			{
				return this._TBL_CARRERAs;
			}
			set
			{
				this._TBL_CARRERAs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_CARRERAs(TBL_CARRERA entity)
		{
			this.SendPropertyChanging();
			entity.TBL_INSTITUCION = this;
		}
		
		private void detach_TBL_CARRERAs(TBL_CARRERA entity)
		{
			this.SendPropertyChanging();
			entity.TBL_INSTITUCION = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_PASANTIA")]
	public partial class TBL_PASANTIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pas_id;
		
		private System.DateTime _pas_fechaini;
		
		private System.DateTime _pas_fechafin;
		
		private int _pas_horas;
		
		private char _pas_status;
		
		private System.DateTime _pas_add;
		
		private int _est_id;
		
		private byte _car_id;
		
		private byte _inst_id;
		
		private int _emp_id;
		
		private int _doc_id;
		
		private int _are_id;
		
		private EntityRef<TBL_ESTUDIANTE> _TBL_ESTUDIANTE;
		
		private EntityRef<TBL_EMPRESA> _TBL_EMPRESA;
		
		private EntityRef<TBL_DOCENTE> _TBL_DOCENTE;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpas_idChanging(int value);
    partial void Onpas_idChanged();
    partial void Onpas_fechainiChanging(System.DateTime value);
    partial void Onpas_fechainiChanged();
    partial void Onpas_fechafinChanging(System.DateTime value);
    partial void Onpas_fechafinChanged();
    partial void Onpas_horasChanging(int value);
    partial void Onpas_horasChanged();
    partial void Onpas_statusChanging(char value);
    partial void Onpas_statusChanged();
    partial void Onpas_addChanging(System.DateTime value);
    partial void Onpas_addChanged();
    partial void Onest_idChanging(int value);
    partial void Onest_idChanged();
    partial void Oncar_idChanging(byte value);
    partial void Oncar_idChanged();
    partial void Oninst_idChanging(byte value);
    partial void Oninst_idChanged();
    partial void Onemp_idChanging(int value);
    partial void Onemp_idChanged();
    partial void Ondoc_idChanging(int value);
    partial void Ondoc_idChanged();
    partial void Onare_idChanging(int value);
    partial void Onare_idChanged();
    #endregion
		
		public TBL_PASANTIA()
		{
			this._TBL_ESTUDIANTE = default(EntityRef<TBL_ESTUDIANTE>);
			this._TBL_EMPRESA = default(EntityRef<TBL_EMPRESA>);
			this._TBL_DOCENTE = default(EntityRef<TBL_DOCENTE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pas_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pas_id
		{
			get
			{
				return this._pas_id;
			}
			set
			{
				if ((this._pas_id != value))
				{
					this.Onpas_idChanging(value);
					this.SendPropertyChanging();
					this._pas_id = value;
					this.SendPropertyChanged("pas_id");
					this.Onpas_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pas_fechaini", DbType="DateTime NOT NULL")]
		public System.DateTime pas_fechaini
		{
			get
			{
				return this._pas_fechaini;
			}
			set
			{
				if ((this._pas_fechaini != value))
				{
					this.Onpas_fechainiChanging(value);
					this.SendPropertyChanging();
					this._pas_fechaini = value;
					this.SendPropertyChanged("pas_fechaini");
					this.Onpas_fechainiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pas_fechafin", DbType="DateTime NOT NULL")]
		public System.DateTime pas_fechafin
		{
			get
			{
				return this._pas_fechafin;
			}
			set
			{
				if ((this._pas_fechafin != value))
				{
					this.Onpas_fechafinChanging(value);
					this.SendPropertyChanging();
					this._pas_fechafin = value;
					this.SendPropertyChanged("pas_fechafin");
					this.Onpas_fechafinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pas_horas", DbType="Int NOT NULL")]
		public int pas_horas
		{
			get
			{
				return this._pas_horas;
			}
			set
			{
				if ((this._pas_horas != value))
				{
					this.Onpas_horasChanging(value);
					this.SendPropertyChanging();
					this._pas_horas = value;
					this.SendPropertyChanged("pas_horas");
					this.Onpas_horasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pas_status", DbType="Char(1) NOT NULL")]
		public char pas_status
		{
			get
			{
				return this._pas_status;
			}
			set
			{
				if ((this._pas_status != value))
				{
					this.Onpas_statusChanging(value);
					this.SendPropertyChanging();
					this._pas_status = value;
					this.SendPropertyChanged("pas_status");
					this.Onpas_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pas_add", DbType="DateTime NOT NULL")]
		public System.DateTime pas_add
		{
			get
			{
				return this._pas_add;
			}
			set
			{
				if ((this._pas_add != value))
				{
					this.Onpas_addChanging(value);
					this.SendPropertyChanging();
					this._pas_add = value;
					this.SendPropertyChanged("pas_add");
					this.Onpas_addChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int est_id
		{
			get
			{
				return this._est_id;
			}
			set
			{
				if ((this._est_id != value))
				{
					if (this._TBL_ESTUDIANTE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onest_idChanging(value);
					this.SendPropertyChanging();
					this._est_id = value;
					this.SendPropertyChanged("est_id");
					this.Onest_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_id", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte car_id
		{
			get
			{
				return this._car_id;
			}
			set
			{
				if ((this._car_id != value))
				{
					if (this._TBL_ESTUDIANTE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncar_idChanging(value);
					this.SendPropertyChanging();
					this._car_id = value;
					this.SendPropertyChanged("car_id");
					this.Oncar_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inst_id", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte inst_id
		{
			get
			{
				return this._inst_id;
			}
			set
			{
				if ((this._inst_id != value))
				{
					if (this._TBL_ESTUDIANTE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oninst_idChanging(value);
					this.SendPropertyChanging();
					this._inst_id = value;
					this.SendPropertyChanged("inst_id");
					this.Oninst_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int emp_id
		{
			get
			{
				return this._emp_id;
			}
			set
			{
				if ((this._emp_id != value))
				{
					if (this._TBL_EMPRESA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onemp_idChanging(value);
					this.SendPropertyChanging();
					this._emp_id = value;
					this.SendPropertyChanged("emp_id");
					this.Onemp_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doc_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int doc_id
		{
			get
			{
				return this._doc_id;
			}
			set
			{
				if ((this._doc_id != value))
				{
					if (this._TBL_DOCENTE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondoc_idChanging(value);
					this.SendPropertyChanging();
					this._doc_id = value;
					this.SendPropertyChanged("doc_id");
					this.Ondoc_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_are_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int are_id
		{
			get
			{
				return this._are_id;
			}
			set
			{
				if ((this._are_id != value))
				{
					if (this._TBL_EMPRESA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onare_idChanging(value);
					this.SendPropertyChanging();
					this._are_id = value;
					this.SendPropertyChanged("are_id");
					this.Onare_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_ESTUDIANTE_TBL_PASANTIA", Storage="_TBL_ESTUDIANTE", ThisKey="est_id,car_id,inst_id", OtherKey="est_id,car_id,inst_id", IsForeignKey=true)]
		public TBL_ESTUDIANTE TBL_ESTUDIANTE
		{
			get
			{
				return this._TBL_ESTUDIANTE.Entity;
			}
			set
			{
				TBL_ESTUDIANTE previousValue = this._TBL_ESTUDIANTE.Entity;
				if (((previousValue != value) 
							|| (this._TBL_ESTUDIANTE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_ESTUDIANTE.Entity = null;
						previousValue.TBL_PASANTIAs.Remove(this);
					}
					this._TBL_ESTUDIANTE.Entity = value;
					if ((value != null))
					{
						value.TBL_PASANTIAs.Add(this);
						this._est_id = value.est_id;
						this._car_id = value.car_id;
						this._inst_id = value.inst_id;
					}
					else
					{
						this._est_id = default(int);
						this._car_id = default(byte);
						this._inst_id = default(byte);
					}
					this.SendPropertyChanged("TBL_ESTUDIANTE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_EMPRESA_TBL_PASANTIA", Storage="_TBL_EMPRESA", ThisKey="emp_id,are_id", OtherKey="emp_id,are_id", IsForeignKey=true)]
		public TBL_EMPRESA TBL_EMPRESA
		{
			get
			{
				return this._TBL_EMPRESA.Entity;
			}
			set
			{
				TBL_EMPRESA previousValue = this._TBL_EMPRESA.Entity;
				if (((previousValue != value) 
							|| (this._TBL_EMPRESA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_EMPRESA.Entity = null;
						previousValue.TBL_PASANTIAs.Remove(this);
					}
					this._TBL_EMPRESA.Entity = value;
					if ((value != null))
					{
						value.TBL_PASANTIAs.Add(this);
						this._emp_id = value.emp_id;
						this._are_id = value.are_id;
					}
					else
					{
						this._emp_id = default(int);
						this._are_id = default(int);
					}
					this.SendPropertyChanged("TBL_EMPRESA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_DOCENTE_TBL_PASANTIA", Storage="_TBL_DOCENTE", ThisKey="doc_id", OtherKey="doc_id", IsForeignKey=true)]
		public TBL_DOCENTE TBL_DOCENTE
		{
			get
			{
				return this._TBL_DOCENTE.Entity;
			}
			set
			{
				TBL_DOCENTE previousValue = this._TBL_DOCENTE.Entity;
				if (((previousValue != value) 
							|| (this._TBL_DOCENTE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_DOCENTE.Entity = null;
						previousValue.TBL_PASANTIAs.Remove(this);
					}
					this._TBL_DOCENTE.Entity = value;
					if ((value != null))
					{
						value.TBL_PASANTIAs.Add(this);
						this._doc_id = value.doc_id;
					}
					else
					{
						this._doc_id = default(int);
					}
					this.SendPropertyChanged("TBL_DOCENTE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_ROL")]
	public partial class TBL_ROL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _rol_id;
		
		private string _rol_descripcion;
		
		private char _rol_status;
		
		private System.DateTime _rol_add;
		
		private EntitySet<TBL_USUARIO> _TBL_USUARIOs;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onrol_idChanging(int value);
    partial void Onrol_idChanged();
    partial void Onrol_descripcionChanging(string value);
    partial void Onrol_descripcionChanged();
    partial void Onrol_statusChanging(char value);
    partial void Onrol_statusChanged();
    partial void Onrol_addChanging(System.DateTime value);
    partial void Onrol_addChanged();
    #endregion
		
		public TBL_ROL()
		{
			this._TBL_USUARIOs = new EntitySet<TBL_USUARIO>(new Action<TBL_USUARIO>(this.attach_TBL_USUARIOs), new Action<TBL_USUARIO>(this.detach_TBL_USUARIOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int rol_id
		{
			get
			{
				return this._rol_id;
			}
			set
			{
				if ((this._rol_id != value))
				{
					this.Onrol_idChanging(value);
					this.SendPropertyChanging();
					this._rol_id = value;
					this.SendPropertyChanged("rol_id");
					this.Onrol_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol_descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string rol_descripcion
		{
			get
			{
				return this._rol_descripcion;
			}
			set
			{
				if ((this._rol_descripcion != value))
				{
					this.Onrol_descripcionChanging(value);
					this.SendPropertyChanging();
					this._rol_descripcion = value;
					this.SendPropertyChanged("rol_descripcion");
					this.Onrol_descripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol_status", DbType="Char(1) NOT NULL")]
		public char rol_status
		{
			get
			{
				return this._rol_status;
			}
			set
			{
				if ((this._rol_status != value))
				{
					this.Onrol_statusChanging(value);
					this.SendPropertyChanging();
					this._rol_status = value;
					this.SendPropertyChanged("rol_status");
					this.Onrol_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol_add", DbType="DateTime NOT NULL")]
		public System.DateTime rol_add
		{
			get
			{
				return this._rol_add;
			}
			set
			{
				if ((this._rol_add != value))
				{
					this.Onrol_addChanging(value);
					this.SendPropertyChanging();
					this._rol_add = value;
					this.SendPropertyChanged("rol_add");
					this.Onrol_addChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_ROL_TBL_USUARIO", Storage="_TBL_USUARIOs", ThisKey="rol_id", OtherKey="rol_id")]
		public EntitySet<TBL_USUARIO> TBL_USUARIOs
		{
			get
			{
				return this._TBL_USUARIOs;
			}
			set
			{
				this._TBL_USUARIOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_USUARIOs(TBL_USUARIO entity)
		{
			this.SendPropertyChanging();
			entity.TBL_ROL = this;
		}
		
		private void detach_TBL_USUARIOs(TBL_USUARIO entity)
		{
			this.SendPropertyChanging();
			entity.TBL_ROL = null;
		}
	}
}
#pragma warning restore 1591
